KS-2-1 arithmetic mean
SuslikkrolArr/KotlinSprint pull request #6
Opened 2024-02-16 23:00 UTC by SuslikkrolArr

2024-02-17 12:10 UTC, ievetrovdev requested changes
Значения в этом коде являются [магическими числами](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)Предлагаю добавить переменные) Согласно условию следует проинициализировать значения, которрые даны в ТЗ. И потом, не совсем корректно с точки зрения логики, количество студентов не может быть вещественным числом (дробным).
Однако, баллы могли бы быть дробными, или же можно применить .toFloat() для суммы оценок в момент подсчета

2024-02-18 02:08 UTC, SuslikkrolArr commented
Я переделал и убрал магические числа. Но про toFloat() не очень понял. У нас этот метод разбирался в видео?

2024-02-19 10:21 UTC, ievetrovdev commented
> Я переделал и убрал магические числа. Но про toFloat() не очень понял. У нас этот метод разбирался в видео?

Метод toFloat() приводит значение числа к типу Float (число с плавающей точкой), также toInt() преобразует значения к целочисленному типу Int

2024-02-19 10:22 UTC, ievetrovdev approved these changes
Теперь все четко!

2024-02-19 10:27 UTC, merged