KS-2-2 employee salaries
SuslikkrolArr/KotlinSprint pull request #7
Opened 2024-02-17 01:20 UTC by SuslikkrolArr

2024-02-17 16:33 UTC, ievetrovdev requested changes

2024-02-17 16:33 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task2.kt
> +    val employeeSalaryExpenses: Int = nemberOfEmployees * 30000
Решение верное, но значения в этом коде являются [магическими числами](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F). Не лучшая практика. Предлагаю добавить переменные)

2024-02-18 01:21 UTC, SuslikkrolArr commented on src/main/kotlin/lesson_2/lesson2_task2.kt
> +    val employeeSalaryExpenses: Int = nemberOfEmployees * 30000
Вообще раньше не знал о термине магические числа, интересно. Окей, переделаю )

2024-02-19 10:14 UTC, ievetrovdev approved these changes
В целом все отлично!

2024-02-19 10:14 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task2.kt
> +    val nemberOfEmployees: Int = 50
Опечатка

2024-02-19 10:14 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task2.kt
> +    val namberOfTrainees: Int = 30
и тут)

2024-02-19 10:36 UTC, merged